### ISSUE TITLE
Unpacked version has some outdated tiles

### ISSUE THREAD

**Issue by ProjectileWaterfowl** [Theawesomeboophis/UndeadPeopleUnpacked#4]
Was looking at rotating around vehicle trunks, and found that the unpacked version has a lot of the old vehicle tiles, and is missing some of the new(er) ones. I've double checked. Might be outdated in other ways, too.

Images for comparison:

Unpacked version
![image](https://user-images.githubusercontent.com/8988919/155935963-7ec13623-fced-429e-bcb8-5f4fe325ad9d.png)
(The unpacked files are the same)

Release version
![image](https://user-images.githubusercontent.com/8988919/155936141-c28d39f8-4ad3-42f1-ba97-f6f34e846226.png)

**Comment by Theawesomeboophis** [comment]
Unpacked is very outdated, this is a known issue and I'm not really sure how to fix it, we've found a way to update vanilla, but we can't update mod tiles through the new method, which stinks. If you or anyone else wants to try to backport the new stuff from packed into here, that would be great and really helpful.

**Comment by ProjectileWaterfowl** [comment]
I'll start slicing up images.

**Comment by ProjectileWaterfowl** [comment]
I've gotten stuff unpacked. Spent half a day working on my own method until I found that scripts already existed to do the exact same thing. Those python scripts in the repo! Unfortunately, the results need to be gone through, named, and sorted manually. It'll be a one-time thing, but still a pain.
